version: '3.8'
services:
  usermanagement-application:
    image: usermanagement-application-image:latest
    ports:
      - "8082:8081"
    depends_on:
      - mysql-db
    networks:
      - user-network
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "Root@123"
      MYSQL_DATABASE: "userdb"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - user-network
volumes:
  mysql-data:
networks:
  user-network:
    driver: bridge